import { ROLES } from './roles'

export const CAPABILITIES = {
  CREATE_POST: 'CREATE_POST',
  EDIT_OWN_POST: 'EDIT_OWN_POST',
  DELETE_OWN_POST: 'DELETE_OWN_POST',

  ACCESS_VENDOR_DASHBOARD: 'ACCESS_VENDOR_DASHBOARD',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
}

const RULES = {

  [ROLES.USER]: [
    CAPABILITIES.CREATE_POST,
    CAPABILITIES.EDIT_OWN_POST,
    CAPABILITIES.DELETE_OWN_POST
  ],
  [ROLES.VENDOR]: [
    CAPABILITIES.CREATE_POST,
    CAPABILITIES.EDIT_OWN_POST,
    CAPABILITIES.DELETE_OWN_POST,
    CAPABILITIES.ACCESS_VENDOR_DASHBOARD,
    CAPABILITIES.MANAGE_PRODUCTS
  ],
  [ROLES.ADMIN]: [
  ]
}

export function checkCapability(role, capability) {
  if (role === ROLES.ADMIN) return true
  const caps = RULES[role] || []
  return caps.includes(capability)
}
